### ISSUE TITLE
Bags and rings after the first are not being consider to be equiped as upgrade

### ISSUE THREAD

**Issue by prot3ct** [AlexFolland/AutoGear#63]
Autogear is not equiping items after the first one. For example upgrades for rings are made only for the ring in slot1.

Same is for bags, only first bag is consider for upgrade.

**Comment by prot3ct** [comment]
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/9fb19561-2d5b-40c9-8f50-a6956c82cb6d)

**Comment by prot3ct** [comment]
In the image u can see I have 3 netherweave bags and 1 frostweave and the frostweave bag in my inventory wont equip, when doing /ag scan

**Comment by AlexFolland** [comment]
Do you have slot-locking enabled?  If so, do you have any slots marked as locked in the slot-locking dropdown?

**Comment by prot3ct** [comment]
no its not enabled, and no slots are marked.

**Comment by AlexFolland** [comment]
The Cataclysm changes are not in a release yet since I haven't seen any testing feedback for them.  Are you using the latest git HEAD from the `master` branch, or just the latest public release, which is an older version?

**Comment by prot3ct** [comment]
I tried with both and this bug is reproduced on both.

**Comment by AlexFolland** [comment]
OK, I reproduced an issue and pushed a fix which might also solve your issue.  After my fix, I was able to do the following successfully:

1. Unequip 2 out of my 4 bags, leaving me with 2 empty slots, a 10-slot bag still equipped, and a 16-slot bag still equipped
2. Buy a 6-slot bag, leaving me with the following bags in my inventory but not equipped: a 6-slot bag, an 8-slot bag, and a 12-slot bag
3. Run the AutoGear scan, which then equipped both the 12-slot bag and the 8-slot bag, in that order, resulting in all the bags with slots higher than 6 being equipped, all at once

Can you please try with the latest git HEAD from the `master` branch and let me know if the issue is resolved or if you can still reproduce it?

**Comment by prot3ct** [comment]
For me this is not working. Everything is like it was before.

**Comment by AlexFolland** [comment]
OK, thanks for the info.  Since I can't reproduce this on my end, I will need to see the specifics of the circumstances under which the issue manifested for you more clearly to be able to solve this.  Can you please reproduce the issue again and show me:

- The output of `/ag spec` in the chat
- The debug tooltips (enable with `/ag debuginfo` or `/ag test`) for all your rings and your bags
- The verbose AutoGear output in the chat when you run a scan and it's not working (switch to verbosity 2 or 3 with `/ag verbosity 2` or `/ag verbosity 3` and then scan with `/ag scan`)

**Comment by prot3ct** [comment]
ok, I will try tonight.

**Comment by prot3ct** [comment]
<img width="1538" alt="image" src="https://github.com/AlexFolland/AutoGear/assets/13061058/23dd91b4-9983-438b-b343-dcf62c8c2bd8">

You can see in the screenshot, I have frostweave bag in my inventory and I dont have bag4 slot equiped at all

**Comment by prot3ct** [comment]
<img width="693" alt="image" src="https://github.com/AlexFolland/AutoGear/assets/13061058/d8beed1b-f897-4511-a5ee-e225482faa4e">

Thats the tooltip of the bag

**Comment by AlexFolland** [comment]
OK.  I can see that you don't have the latest version, since I fixed the Pawn debug tooltip info.  It should say "Pawn says item can't have stats" beside "Pawn value", not "nil item data".  Can you please install the latest version and try again?

**Comment by prot3ct** [comment]
Latest master doesnt work as well. Here is screenshot
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/8ba2fabc-dbae-433e-aed1-af821b53045e)

**Comment by AlexFolland** [comment]
I did some major refactors which might include fixing this bug.  Can you please test again with the latest commit in `master` as of now?  I couldn't reproduce the bug in a lot of testing with bags and empty bag slots, etc., so it may be resolved.

**Comment by prot3ct** [comment]
Tried with latest master as of now. Bug is still happening everytime.

**Comment by AlexFolland** [comment]
I'll need more information to figure this out.  There's no clear way for this to happen in the code base, so I need the debug info tooltips for all of your bags.  I made many changes to the code, so it is useful to see these tooltips with the latest.

By the way, I noticed your screenshots are a little awkward (stretched and such), meaning I expect you're doing something unnecessarily difficult to send these screenshots.  An easier way in Windows is to press Super+Shift+S to run the snipping tool, drag a rectangle that covers the tooltip, focus the comment box on GitHub, and simply paste from the clipboard (Shift+Insert or Ctrl+V usually).  Pasting image data into the GitHub comment box causes your browser to upload the image to GitHub and generate the correct image tag, so you don't have to use any third-party tools or hosts, or write the image tag yourself.

I personally use Flameshot on both Linux and Windows, but the Windows snipping tool and GitHub together get the job done basically.

By the way, this issue is extremely difficult to solve on my own since I can't reproduce it and I feel like I have an even-more complicated situation than you're showing with bag equipping.  I want to fix it, but I really need your help since it makes no sense right now.

**Comment by AlexFolland** [comment]
I've pushed and released another change which might resolve this.  Can you please give it a try?

**Comment by prot3ct** [comment]
I tested with latest master, bug is still present.

I am atatchin screenshots of each bag debuginfo here.
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/f651e446-bc32-4067-b2e3-af06cd012806)
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/e3a4961e-44db-4c5a-a091-289ec0be9c39)
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/89b7f045-2fe3-4056-8cab-8e14e97dd453)
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/0e32af55-a11a-4e4d-85d2-8b54f8a11359)

This bug aplies to ring 2 and trinket 2 as well. 2nd ring and 2nd trinket

**Comment by AlexFolland** [comment]
Please use the latest version of AutoGear.  I have removed a bag on my end and I see the empty slot as I had fixed after your initial report.  If you're not seeing that, you must not be using the latest version of AutoGear, from either CurseForge or GitHub.

![image](https://github.com/AlexFolland/AutoGear/assets/601517/6600e78c-a7fb-42e1-8327-daede4f47c91)

This shows that AutoGear does see the empty bag slot and sees that it has 0 score.

**Comment by prot3ct** [comment]
Ok literally tried multiple times with latest master and latest from Curseforge, I am not getting 0 score on this.

**Comment by AlexFolland** [comment]
I think you must be extracting the addon to the wrong directory or something like that.  The behavior in your screenshots does not match the behavior of the latest version.  Maybe you're updating the `_classic_era_` addons directory and not the `_classic_` addons directory.

**Comment by AlexFolland** [comment]
It's especially telling that you don't have a "soulbinding" line in your debug info.  That would not be missing in the latest version.

**Comment by prot3ct** [comment]
Ok, my bags with soulbiding, thats latest master for sure, I double-checked.

![image](https://github.com/AlexFolland/AutoGear/assets/13061058/1f1414e0-219d-45b6-9b94-f890afcdcb54)
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/4c07cb12-6711-4ec9-9c5f-0ffbab9185fd)
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/5cef70a0-1b89-4d77-82a7-6dc6794ea7b1)
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/568ca8a9-d652-40ef-a09f-679d9711e111)

**Comment by AlexFolland** [comment]
Thanks for updating.  I still can't reproduce this, even with all other addons disabled.  Can you please disable all other addons and try again, including an `/ag scan` with the bag not equipped?

**Comment by AlexFolland** [comment]
I committed some changes which should give more information in the tooltip for bags, especially with empty bag slots.  Can you please get the latest changes from the `master` branch and try it, then paste screenshots here?

**Comment by AlexFolland** [comment]
I fixed another issue which may have caused this behavior yesterday and released the fix.  I think this must now finally be resolved, so I'm closing the ticket now.  Please let me know if you can still reproduce this and I'll reopen the ticket.  Thanks for your report and your consistent responses.
